/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ivan Norman (https://sketchfab.com/vanidza)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/low-poly-truck-car-drifter-f3750246b6564607afbefc61cb1683b1
title: Low-poly truck (car "Drifter")
*/

import React, { useRef } from 'react';
import * as THREE from 'three';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ color, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/drifter.glb');
  const { actions } = useAnimations(animations, group);

  const modelColor = new THREE.Color(color);

  return (
    <group ref={group} scale={[0.1, 0.1, 0.1]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[155.62, 20.72, -81.96]} rotation={[-0.21, Math.PI / 2, 0]} scale={2.8}>
            <mesh geometry={nodes.Spring_Light_black_0.geometry} material={nodes.Spring_Light_black_0.material} />
            <mesh geometry={nodes.Spring_Black_0.geometry} material={nodes.Spring_Black_0.material} />
          </group>
          <group position={[-128.51, 20.72, -81.96]} rotation={[-0.21, Math.PI / 2, 0]} scale={2.8}>
            <mesh geometry={nodes.Spring001_Light_black_0.geometry} material={nodes.Spring001_Light_black_0.material} />
            <mesh geometry={nodes.Spring001_Black_0.geometry} material={nodes.Spring001_Black_0.material} />
          </group>
          <group position={[155.62, 20.72, 81.96]} rotation={[0.21, -Math.PI / 2, 0]} scale={2.8}>
            <mesh geometry={nodes.Spring002_Light_black_0.geometry} material={nodes.Spring002_Light_black_0.material} />
            <mesh geometry={nodes.Spring002_Black_0.geometry} material={nodes.Spring002_Black_0.material} />
          </group>
          <group position={[-128.51, 20.72, 81.96]} rotation={[0.21, -Math.PI / 2, 0]} scale={2.8}>
            <mesh geometry={nodes.Spring003_Light_black_0.geometry} material={nodes.Spring003_Light_black_0.material} />
            <mesh geometry={nodes.Spring003_Black_0.geometry} material={nodes.Spring003_Black_0.material} />
          </group>
          <group position={[70.41, 165.26, 94.26]} scale={0}>
            <mesh geometry={nodes.Smoke001_Smoke_0.geometry} material={nodes.Smoke001_Smoke_0.material} />
          </group>
          <group position={[74.6, 165.67, 92.36]} scale={0}>
            <mesh geometry={nodes.Smoke002_Smoke_0.geometry} material={nodes.Smoke002_Smoke_0.material} />
          </group>
          <group position={[72.18, 166.53, 95.14]} scale={0}>
            <mesh geometry={nodes.Smoke003_Smoke_0.geometry} material={nodes.Smoke003_Smoke_0.material} />
          </group>
          <group position={[73.14, 165.64, 93.1]} scale={0}>
            <mesh geometry={nodes.Smoke004_Smoke_0.geometry} material={nodes.Smoke004_Smoke_0.material} />
          </group>
          <group position={[75.2, 166.04, 95.17]} scale={0}>
            <mesh geometry={nodes.Smoke005_Smoke_0.geometry} material={nodes.Smoke005_Smoke_0.material} />
          </group>
          <group position={[75.86, 167.36, 89.87]} scale={0}>
            <mesh geometry={nodes.Smoke006_Smoke_0.geometry} material={nodes.Smoke006_Smoke_0.material} />
          </group>
          <group position={[74.99, 167.94, 90.93]} scale={0}>
            <mesh geometry={nodes.Smoke007_Smoke_0.geometry} material={nodes.Smoke007_Smoke_0.material} />
          </group>
          <group position={[73.57, 166.39, 94.53]} scale={0}>
            <mesh geometry={nodes.Smoke008_Smoke_0.geometry} material={nodes.Smoke008_Smoke_0.material} />
          </group>
          <group position={[70.76, 159.59, 95.08]} scale={0}>
            <mesh geometry={nodes.Smoke009_Smoke_0.geometry} material={nodes.Smoke009_Smoke_0.material} />
          </group>
          <group position={[72.88, 163.49, 92.99]} scale={0}>
            <mesh geometry={nodes.Smoke010_Smoke_0.geometry} material={nodes.Smoke010_Smoke_0.material} />
          </group>
          <group position={[75.05, 162.61, 91.64]} scale={0}>
            <mesh geometry={nodes.Smoke011_Smoke_0.geometry} material={nodes.Smoke011_Smoke_0.material} />
          </group>
          <group position={[73.82, 161.82, 89.95]} scale={0}>
            <mesh geometry={nodes.Smoke012_Smoke_0.geometry} material={nodes.Smoke012_Smoke_0.material} />
          </group>
          <group name="Frame" rotation={[-Math.PI / 2, 0, 0]} scale={[300, 100, 50]}>
            <mesh geometry={nodes.Frame_Orange_0.geometry} material={materials.Orange} material-color={modelColor} />
            <mesh geometry={nodes.Frame_Black_0.geometry} material={nodes.Frame_Black_0.material} />
            <mesh geometry={nodes.Frame_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Frame_Light_0.geometry} material={materials.Light} />
            <mesh geometry={nodes.Frame_Light_red_0.geometry} material={materials.Light_red} />
            <mesh geometry={nodes.Frame_Dark_brown_0.geometry} material={materials.Dark_brown} />
            <mesh geometry={nodes.Frame_Dark_brown_handle_0.geometry} material={materials.Dark_brown_handle} />
            <mesh geometry={nodes.Frame_Glass_trailer_0.geometry} material={materials.Glass_trailer} />
            <mesh geometry={nodes.Frame_Light_black_0.geometry} material={nodes.Frame_Light_black_0.material} />
            <mesh geometry={nodes.Frame_Brown_0.geometry} material={materials.Brown} />
          </group>
          <group position={[155.62, 9.27, -127.28]} rotation={[0, 0, -1.4]} scale={[50.1, 50.1, 27.01]}>
            <mesh geometry={nodes.Front_wheel_Black_0.geometry} material={nodes.Front_wheel_Black_0.material} />
            <mesh geometry={nodes.Front_wheel_Light_black_0.geometry} material={nodes.Front_wheel_Light_black_0.material} />
          </group>
          <group position={[-128.51, 14.27, -125.98]} rotation={[0, 0, -2.16]} scale={[55.11, 55.11, 29.62]}>
            <mesh geometry={nodes.Rear_wheel_Black_0.geometry} material={nodes.Rear_wheel_Black_0.material} />
            <mesh geometry={nodes.Rear_wheel_Light_black_0.geometry} material={nodes.Rear_wheel_Light_black_0.material} />
          </group>
          <group position={[155.62, 9.27, 127.28]} rotation={[Math.PI, 0, 1.31]} scale={[50.1, 50.1, 27.01]}>
            <mesh geometry={nodes.Front_wheel001_Black_0.geometry} material={nodes.Front_wheel001_Black_0.material} />
            <mesh geometry={nodes.Front_wheel001_Light_black_0.geometry} material={nodes.Front_wheel001_Light_black_0.material} />
          </group>
          <group position={[-128.51, 14.27, 125.98]} rotation={[Math.PI, 0, 2.13]} scale={[55.11, 55.11, 29.62]}>
            <mesh geometry={nodes.Rear_wheel001_Black_0.geometry} material={nodes.Rear_wheel001_Black_0.material} />
            <mesh geometry={nodes.Rear_wheel001_Light_black_0.geometry} material={nodes.Rear_wheel001_Light_black_0.material} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/drifter.glb');
